version: "3.4"
services:

  backend:
    image: ${CI_REGISTRY_IMAGE}/dumplings-store-backend:latest
    container_name: backend
    expose:
      - "8081"
    healthcheck:
      test: curl --fail -s http://localhost:8081/health
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dumplings_network
    restart: always

  frontend:
    image: ${CI_REGISTRY_IMAGE}/dumplings-store-frontend:latest
    container_name: frontend
    ports:
      - '80:80'
    volumes:
      - /home/deploy-user/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      DEFAULT_HOST: backend
    networks:
      - dumplings_network
    restart: always

networks:
  dumplings_network:
    name: dumplings_network