name: frontend
app: frontend
registryUrl: "gitlab.praktikum-services.ru:5050/std-014-19/nk-dumplings"
#ingress.yaml
ingress:
  ingressClassName: "nginx"
  pathType: Prefix
  portNumber: 80
#service.yaml
selector:
  app: frontend
ports:
  port: 80
  protocol: TCP
  targetPort: 80
#deployment.yaml
revisionHistoryLimit: 15
replicas: 1
imageDir: "/dumplings-store-frontend"
containerPort: 80
volumeMounts:
  name: nginx-conf
  mountPath: /etc/nginx/conf.d/default.conf
  subPath: nginx.conf
  readOnly: true
volumes:
  name: nginx-conf
  configMap:
    name: nginx-conf
    items:
      key: nginx.conf
      path: nginx.conf

### Prometheus
prometheus_exporter: nginx/nginx-prometheus-exporter:0.10.0
annotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "9113"
  prometheus.io/scrape: "true"
service:
  port: 80
