---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  revisionHistoryLimit: 15
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/std-014-19/nk-dumplings/dumplings-store-backend:latest
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-dumplings-config-secret
