apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.app }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.port }}
      protocol: {{ .Values.ports.protocol }}
      targetPort: {{ .Values.ports.targetPort }}
  selector:
    app: {{ .Release.Name}}-{{ .Values.selector.app }}
