---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.app }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.app }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.ports.port }}
      protocol: {{ .Values.service.ports.protocol}}
      targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.selector.app }}
